### ISSUE TITLE
Old github repo links

### ISSUE THREAD

**Issue by delirious-lettuce** [GitMeet/GitMeet-main#7]
https://github.com/GitMeet/GitMeet-main/blob/0ef238feba283f3a249970dfede56042baf8d5c6/recruitapp/templates/new_home.html#L469

https://github.com/GitMeet/GitMeet-main/blob/0ef238feba283f3a249970dfede56042baf8d5c6/recruitapp/temporary_home.html#L375

https://github.com/GitMeet/GitMeet-main/blob/0ef238feba283f3a249970dfede56042baf8d5c6/recruitapp/original_new_home.html#L416

Shouldn't it be `https://github.com/GitMeet/GitMeet-main/issues`?

**Comment by GitMeet** [comment]
Thank you very much for pointing that out. I have fixed it.
